# Generated by Django 2.2 on 2019-05-30 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'owner invitation',
                'verbose_name_plural': 'owner invitations',
            },
        ),
        migrations.CreateModel(
            name='PublicAuthorization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('hash_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('closing_date', models.DateField(blank=True, null=True, verbose_name='closing date')),
                ('congressman', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authorizations', to='projects.DocumentResponsible', verbose_name='congressman')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorization_emails', to='participations.InvitedGroup', verbose_name='group')),
            ],
            options={
                'verbose_name': 'public authorization',
                'verbose_name_plural': 'public authorization',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('message', models.TextField()),
                ('was_read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
            },
        ),
        migrations.CreateModel(
            name='ParcipantInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('email', models.EmailField(max_length=254)),
                ('hash_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('accepted', models.BooleanField(default=False, verbose_name='accepted')),
                ('answered', models.BooleanField(default=False, verbose_name='answered')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invited_emails', to='participations.InvitedGroup', verbose_name='group')),
            ],
            options={
                'verbose_name': 'participant invitation',
                'verbose_name_plural': 'participant invitations',
                'unique_together': {('email', 'group')},
            },
        ),
    ]
