# Generated by Django 2.1.3 on 2018-11-21 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participations', '0001_initial'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InvitedEmail',
            new_name='ParcipantInvitation',
        ),
    ]
