# Generated by Django 2.2.5 on 2019-12-03 19:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('participations', '0002_invitedgroup_final_version'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackAuthorization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('video_id', models.CharField(max_length=50, verbose_name='video id')),
                ('hash_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_authorizations', to='participations.InvitedGroup', verbose_name='group')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_authorizations', to='projects.DocumentVersion', verbose_name='version')),
            ],
            options={
                'verbose_name': 'feedback authorization',
                'verbose_name_plural': 'feedback authorization',
            },
        ),
    ]
