# Generated by Django 2.1.3 on 2018-11-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20181121_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'owner invitation',
                'verbose_name_plural': 'owner invitations',
            },
        ),
        migrations.AlterModelOptions(
            name='parcipantinvitation',
            options={'verbose_name': 'participant invitation', 'verbose_name_plural': 'participant invitations'},
        ),
    ]
