# Generated by Django 2.1.3 on 2018-11-26 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20181122_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcipantinvitation',
            name='answered',
            field=models.BooleanField(default=False, verbose_name='answered'),
        ),
    ]
