# Generated by Django 2.1.5 on 2019-05-15 15:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('participations', '0012_invitedgroup_group_status'),
        ('notifications', '0004_parcipantinvitation_answered'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicAuthorization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('congressman_email', models.EmailField(max_length=254)),
                ('hash_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorization_emails', to='participations.InvitedGroup', verbose_name='group')),
            ],
            options={
                'verbose_name': 'public authorization',
                'verbose_name_plural': 'public authorization',
            },
        ),
    ]
