# Generated by Django 2.1.5 on 2019-05-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_publicauthorization'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicauthorization',
            name='closing_date',
            field=models.DateField(blank=True, null=True, verbose_name='closing date'),
        ),
    ]
