# Generated by Django 2.1.5 on 2019-05-21 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_auto_20190521_1003'),
        ('notifications', '0006_publicauthorization_closing_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicauthorization',
            name='congressman_email',
        ),
        migrations.AddField(
            model_name='publicauthorization',
            name='congressman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authorizations', to='projects.DocumentResponsible', verbose_name='congressman'),
        ),
    ]
