language: python
python:
- "3.6"
- "3.6-dev"  # 3.6 development branch
- "3.7-dev"  # 3.7 development branch
matrix:
  allow_failures:
  - python: 3.5-dev
  - python: 3.6-dev
  - python: 3.7-dev
before_install:
- nvm install 7.2.0
- nvm use 7.2.0
install:
- pip install pipenv
- pipenv install
- npm install
script:
- coverage run src/manage.py test
- flake8 src
- npm run lint
after_success:
- coveralls
