# Generated by Django 2.1.3 on 2018-11-28 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20181121_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='icons/', verbose_name='icon'),
        ),
    ]
