# Generated by Django 2.1.3 on 2018-11-29 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_theme_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcerptType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='excerpt type')),
                ('slug', models.SlugField()),
                ('align_center', models.BooleanField(default=False, verbose_name='align center')),
            ],
            options={
                'verbose_name': 'excerpt type',
                'verbose_name_plural': 'excerpt types',
            },
        ),
        migrations.AlterField(
            model_name='excerpt',
            name='excerpt_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.ExcerptType', verbose_name='excerpt type'),
        ),
    ]
