# Generated by Django 2.1.4 on 2018-12-13 16:57

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20181129_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='color',
            field=colorful.fields.RGBColorField(default='#000'),
            preserve_default=False,
        ),
    ]
