# Generated by Django 2.1.4 on 2018-12-20 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_theme_color'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('document_type', 'number', 'year')},
        ),
    ]
