# Generated by Django 2.1.4 on 2018-12-21 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20181220_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('author_type', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Document Author',
                'verbose_name_plural': 'Document Authors',
            },
        ),
        migrations.CreateModel(
            name='DocumentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_id', models.PositiveIntegerField(default=0, verbose_name='CD ID')),
                ('abridgement', models.TextField(blank=True, null=True, verbose_name='abridgement')),
                ('status', models.CharField(blank=True, max_length=250, null=True, verbose_name='status')),
                ('legislative_body', models.CharField(blank=True, max_length=250, null=True, verbose_name='legislative body')),
                ('keywords', models.TextField(blank=True, null=True, verbose_name='keywords')),
                ('authors', models.ManyToManyField(blank=True, related_name='documents', to='projects.DocumentAuthor')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='infos', to='projects.Document', verbose_name='document')),
            ],
            options={
                'verbose_name': 'Document Information',
                'verbose_name_plural': 'Document Informations',
            },
        ),
    ]
