# Generated by Django 2.1.5 on 2019-01-22 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_documentauthor_documentinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='title')),
                ('video_id', models.CharField(max_length=200, verbose_name='youtube id')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='projects.Document', verbose_name='document')),
            ],
            options={
                'verbose_name': 'document video',
                'verbose_name_plural': 'document videos',
            },
        ),
    ]
