# Generated by Django 2.2 on 2019-04-29 16:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_documentauthorinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='excerpt',
            options={'ordering': ('version', 'order', 'id'), 'verbose_name': 'excerpt', 'verbose_name_plural': 'excerpts'},
        ),
        migrations.RemoveField(
            model_name='excerpt',
            name='parent',
        ),
        migrations.AddField(
            model_name='document',
            name='version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='excerpt',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='excerpt',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='excerpt',
            name='version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.TextField(default='Document description', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(default='Untitled Document', max_length=200, verbose_name='title'),
        ),
    ]
