# Generated by Django 2.2 on 2019-04-29 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20190429_1604'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='excerpt',
            options={'ordering': ('-version', 'order', 'id'), 'verbose_name': 'excerpt', 'verbose_name_plural': 'excerpts'},
        ),
    ]
