# Generated by Django 2.1.5 on 2019-05-21 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20190429_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentResponsible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('cd_id', models.PositiveIntegerField(default=0, verbose_name='CD ID')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='image url')),
                ('party_initials', models.CharField(blank=True, max_length=250, null=True, verbose_name='party initials')),
                ('uf', models.CharField(blank=True, max_length=250, null=True, verbose_name='uf')),
                ('email', models.EmailField(blank=True, max_length=250, null=True, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=250, null=True, verbose_name='phone')),
            ],
            options={
                'verbose_name': 'Document Responsible',
                'verbose_name_plural': 'Document Responsibles',
            },
        ),
        migrations.AddField(
            model_name='document',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='projects.DocumentResponsible', verbose_name='responsible'),
        ),
    ]
