# Generated by Django 2.2 on 2019-05-09 14:29

from django.db import migrations, models
import django.db.models.deletion


def create_document_versions(apps, schema_editor):
    Document = apps.get_model('projects', 'Document')
    DocumentVersion = apps.get_model('projects', 'DocumentVersion')

    for document in Document.objects.all():
        DocumentVersion.objects.create(
            document=document,
            number=document.version
        )


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20190429_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('number', models.PositiveIntegerField(default=0)),
                ('auto_save', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='projects.Document', verbose_name='document')),
            ],
            options={
                'verbose_name': 'document version',
                'verbose_name_plural': 'document versions',
                'ordering': ['-created'],
            },
        ),
        migrations.RunPython(
            create_document_versions
        ),
        migrations.RemoveField(
            model_name='document',
            name='version',
        ),
    ]
