# Generated by Django 2.2 on 2019-05-14 15:50

from django.db import migrations, models
import django.db.models.deletion


def set_default_version(apps, schema_editor):
    Excerpt = apps.get_model('projects', 'Excerpt')

    for excerpt in Excerpt.objects.all():
        last_version = excerpt.document.versions.first()
        excerpt.version = last_version
        excerpt.save()


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_auto_20190509_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excerpt',
            name='version',
        ),
        migrations.AddField(
            model_name='excerpt',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excerpts', to='projects.DocumentVersion', verbose_name='version', null=True),
        ),
        migrations.RunPython(
            set_default_version
        ),
        migrations.AlterField(
            model_name='excerpt',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excerpts', to='projects.DocumentVersion', verbose_name='version'),
        ),
        migrations.AlterUniqueTogether(
            name='documentversion',
            unique_together={('document', 'number')},
        ),
    ]
