# Generated by Django 2.2 on 2019-05-15 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_auto_20190514_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentversion',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='projects.DocumentVersion', verbose_name='parent'),
        ),
    ]
