# Generated by Django 2.2 on 2019-05-21 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_documentversion_parent'),
        ('projects', '0014_auto_20190521_1003'),
    ]

    operations = [
    ]
