# Generated by Django 2.2.19 on 2021-03-30 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VotesReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('start_date', models.DateField(db_index=True, verbose_name='start date')),
                ('end_date', models.DateField(db_index=True, verbose_name='end date')),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('all', 'All the time')], db_index=True, default='daily', max_length=200, verbose_name='period')),
                ('votes', models.IntegerField(blank=True, default=0, null=True, verbose_name='votes')),
            ],
            options={
                'verbose_name': 'vote',
                'verbose_name_plural': 'votes',
                'unique_together': {('start_date', 'period')},
            },
        ),
        migrations.CreateModel(
            name='ParticipantsReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('start_date', models.DateField(db_index=True, verbose_name='start date')),
                ('end_date', models.DateField(db_index=True, verbose_name='end date')),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('all', 'All the time')], db_index=True, default='daily', max_length=200, verbose_name='period')),
                ('participants', models.IntegerField(blank=True, default=0, null=True, verbose_name='participants')),
            ],
            options={
                'verbose_name': 'participant',
                'verbose_name_plural': 'participants',
                'unique_together': {('start_date', 'period')},
            },
        ),
        migrations.CreateModel(
            name='OpinionsReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('start_date', models.DateField(db_index=True, verbose_name='start date')),
                ('end_date', models.DateField(db_index=True, verbose_name='end date')),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('all', 'All the time')], db_index=True, default='daily', max_length=200, verbose_name='period')),
                ('opinions', models.IntegerField(blank=True, default=0, null=True, verbose_name='opinions')),
            ],
            options={
                'verbose_name': 'opinion',
                'verbose_name_plural': 'opinions',
                'unique_together': {('start_date', 'period')},
            },
        ),
        migrations.CreateModel(
            name='NewUsersReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('start_date', models.DateField(db_index=True, verbose_name='start date')),
                ('end_date', models.DateField(db_index=True, verbose_name='end date')),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('all', 'All the time')], db_index=True, default='daily', max_length=200, verbose_name='period')),
                ('new_users', models.IntegerField(blank=True, default=0, null=True, verbose_name='new users')),
            ],
            options={
                'verbose_name': 'new user',
                'verbose_name_plural': 'new users',
                'unique_together': {('start_date', 'period')},
            },
        ),
        migrations.CreateModel(
            name='DocumentsReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('start_date', models.DateField(db_index=True, verbose_name='start date')),
                ('end_date', models.DateField(db_index=True, verbose_name='end date')),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('all', 'All the time')], db_index=True, default='daily', max_length=200, verbose_name='period')),
                ('documents', models.IntegerField(blank=True, default=0, null=True, verbose_name='documents')),
            ],
            options={
                'verbose_name': 'document',
                'verbose_name_plural': 'documents',
                'unique_together': {('start_date', 'period')},
            },
        ),
    ]
