# Generated by Django 2.1.3 on 2018-11-21 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181120_1513'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invitedemail',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='invitedemail',
            name='group',
        ),
        migrations.DeleteModel(
            name='InvitedEmail',
        ),
    ]
