# Generated by Django 2.1.3 on 2018-11-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20181121_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_type',
            field=models.CharField(choices=[('owner', 'Document Owner'), ('defult', 'Default')], default='defult', max_length=200, verbose_name='profile type'),
        ),
    ]
