# Generated by Django 2.2 on 2019-05-30 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitedGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('openning_date', models.DateField(blank=True, null=True, verbose_name='openning date')),
                ('closing_date', models.DateField(verbose_name='closing date')),
                ('public_participation', models.BooleanField(default=False, verbose_name='public participation')),
                ('document_version', models.PositiveIntegerField(default=0)),
                ('text_version', models.PositiveIntegerField(default=0)),
                ('group_status', models.CharField(choices=[('waiting', 'Waiting'), ('in_progress', 'In Progress')], default='in_progress', max_length=200, verbose_name='group status')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invited_groups', to='projects.Document', verbose_name='document')),
                ('thematic_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invited_groups', to='accounts.ThematicGroup', verbose_name='thematic group')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invited_groups', to='projects.DocumentVersion', verbose_name='version')),
            ],
            options={
                'verbose_name': 'invited group',
                'verbose_name_plural': 'invited groups',
            },
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('selected_text', models.TextField(verbose_name='selected text')),
                ('start_index', models.PositiveIntegerField(default=0, verbose_name='start index')),
                ('end_index', models.PositiveIntegerField(default=0, verbose_name='end index')),
                ('content', models.TextField(verbose_name='content')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('excerpt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='projects.Excerpt', verbose_name='excerpt')),
                ('invited_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='participations.InvitedGroup', verbose_name='invited group')),
            ],
            options={
                'verbose_name': 'suggestion',
                'verbose_name_plural': 'suggestions',
                'ordering': ('start_index',),
            },
        ),
        migrations.CreateModel(
            name='OpinionVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('opinion_vote', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject'), ('neutral', 'Neutral')], max_length=200, verbose_name='opinion type')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
                ('suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='participations.Suggestion', verbose_name='suggestion')),
            ],
            options={
                'verbose_name': 'opinion vote',
                'verbose_name_plural': 'opinion votes',
                'unique_together': {('suggestion', 'owner')},
            },
        ),
    ]
