# Generated by Django 2.1.3 on 2018-11-20 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amendment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('content', models.TextField(verbose_name='content')),
                ('amendment_type', models.CharField(choices=[('additive', 'Additive'), ('modifier', 'Modifier'), ('supress', 'Supress')], max_length=200, verbose_name='amendment type')),
                ('excerpt_type', models.CharField(blank=True, choices=[('book', 'Book'), ('chapter', 'Chapter'), ('title', 'Title'), ('section', 'Section'), ('subsection', 'Subsection'), ('article', 'Article'), ('paragraph', 'Paragraph'), ('item', 'Item'), ('line', 'Line'), ('point', 'Point'), ('quote', 'Quote')], max_length=200, null=True, verbose_name='excerpt type')),
                ('number', models.PositiveIntegerField(blank=True, null=True, verbose_name='number')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amendments', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('excerpt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amendments', to='projects.Excerpt', verbose_name='excerpt')),
            ],
            options={
                'verbose_name': 'amendment',
                'verbose_name_plural': 'amendments',
            },
        ),
        migrations.CreateModel(
            name='InvitedGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('closing_date', models.DateField(verbose_name='closing date')),
                ('is_open', models.BooleanField(default=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invited_groups', to='projects.Document', verbose_name='document')),
                ('thematic_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invited_groups', to='accounts.ThematicGroup', verbose_name='thematic group')),
            ],
            options={
                'verbose_name': 'invited group',
                'verbose_name_plural': 'invited groups',
            },
        ),
        migrations.CreateModel(
            name='OpinionVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('opinion_vote', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject'), ('neutral', 'Neutral')], max_length=200, verbose_name='opinion type')),
                ('excerpt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='projects.Excerpt', verbose_name='excerpt')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'opinion vote',
                'verbose_name_plural': 'opinion votes',
            },
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('start_index', models.PositiveIntegerField(verbose_name='start index')),
                ('end_index', models.PositiveIntegerField(verbose_name='end index')),
                ('content', models.TextField(verbose_name='content')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('excerpt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='projects.Excerpt', verbose_name='excerpt')),
                ('invited_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='participations.InvitedGroup', verbose_name='invited group')),
            ],
            options={
                'verbose_name': 'suggestion',
                'verbose_name_plural': 'suggestions',
            },
        ),
        migrations.AddField(
            model_name='opinionvote',
            name='suggestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='participations.Suggestion', verbose_name='suggestion'),
        ),
        migrations.AddField(
            model_name='amendment',
            name='invited_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amendments', to='participations.InvitedGroup', verbose_name='invited group'),
        ),
    ]
