# Generated by Django 2.2.5 on 2019-11-19 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('participations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitedgroup',
            name='final_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invited_groups_final', to='projects.DocumentVersion', verbose_name='final version'),
        ),
    ]
