# Generated by Django 2.1.3 on 2018-11-21 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitedgroup',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
    ]
