# Generated by Django 2.2.5 on 2019-12-26 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participations', '0002_invitedgroup_final_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitedgroup',
            name='group_status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('analyzing', 'Analyzing'), ('in_progress', 'In Progress'), ('waiting_feedback', 'Waiting Feedback')], default='in_progress', max_length=200, verbose_name='group status'),
        ),
    ]
