# Generated by Django 2.2.8 on 2020-02-12 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participations', '0003_auto_20191226_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitedgroup',
            name='group_status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('in_progress', 'In Progress'), ('waiting_feedback', 'Waiting Feedback'), ('analyzing', 'Analyzing'), ('finished', 'Finished')], default='in_progress', max_length=200, verbose_name='group status'),
        ),
    ]
