# Generated by Django 2.1.3 on 2018-11-29 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('participations', '0003_auto_20181123_1535'),
        ('projects', '0004_auto_20181129_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amendment',
            name='excerpt_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.ExcerptType', verbose_name='excerpt type'),
        ),
    ]
