# Generated by Django 2.1.3 on 2018-11-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participations', '0003_auto_20181123_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestion',
            name='end_index',
        ),
        migrations.RemoveField(
            model_name='suggestion',
            name='start_index',
        ),
        migrations.AddField(
            model_name='suggestion',
            name='selected_text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
