# Generated by Django 2.1.3 on 2018-11-26 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participations', '0004_auto_20181126_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitedgroup',
            name='is_open',
        ),
        migrations.AddField(
            model_name='invitedgroup',
            name='public_participation',
            field=models.BooleanField(default=False, verbose_name='public participation'),
        ),
    ]
