# Generated by Django 2.1.3 on 2018-11-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participations', '0005_auto_20181126_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='end_index',
            field=models.PositiveIntegerField(default=0, verbose_name='end index'),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='start_index',
            field=models.PositiveIntegerField(default=0, verbose_name='start index'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='selected_text',
            field=models.TextField(verbose_name='selected text'),
        ),
    ]
