# Generated by Django 2.1.3 on 2018-11-29 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participations', '0006_auto_20181127_1403'),
        ('participations', '0004_auto_20181129_1433'),
    ]

    operations = [
    ]
