# Generated by Django 2.2 on 2019-04-29 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participations', '0009_invitedgroup_clusters'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amendment',
            options={'ordering': ('version', 'order', 'id'), 'verbose_name': 'amendment', 'verbose_name_plural': 'amendments'},
        ),
        migrations.RemoveField(
            model_name='amendment',
            name='amendment_type',
        ),
        migrations.RemoveField(
            model_name='amendment',
            name='excerpt',
        ),
        migrations.AddField(
            model_name='amendment',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='order'),
        ),
        migrations.AddField(
            model_name='amendment',
            name='version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='invitedgroup',
            name='document_version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='invitedgroup',
            name='text_version',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
