# Generated by Django 2.2 on 2019-04-29 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participations', '0010_auto_20190429_1604'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amendment',
            options={'ordering': ('-version', 'order', 'id'), 'verbose_name': 'amendment', 'verbose_name_plural': 'amendments'},
        ),
        migrations.AddField(
            model_name='invitedgroup',
            name='version',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
