# Generated by Django 2.2 on 2019-05-24 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participations', '0013_auto_20190514_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitedgroup',
            name='openning_date',
            field=models.DateField(blank=True, null=True, verbose_name='openning date'),
        ),
    ]
